'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class dtproperty
    Public Property id As Integer
    Public Property objectid As Nullable(Of Integer)
    Public Property [property] As String
    Public Property value As String
    Public Property uvalue As String
    Public Property lvalue As Byte()
    Public Property version As Integer

End Class
