'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Log
    Public Property rid As Integer
    Public Property LogType As String
    Public Property LogCrit As String
    Public Property LogDTM As Date
    Public Property UserId As String
    Public Property RefNum As String
    Public Property LogMsg As String

End Class
