'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace testDashUmm2Service
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FilterData", [Namespace]:="http://schemas.datacontract.org/2004/07/WWTS.ServiceApp"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FilterData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ColField As testDashUmm2Service.Col
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustAssocField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsCallDetailField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrgBranchListField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrgFilterListField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrgFilterTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrgTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RowsField() As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserPermissionField As testDashUmm2Service.UserPermission
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VendorCodeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Col() As testDashUmm2Service.Col
            Get
                Return Me.ColField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ColField, value) <> true) Then
                    Me.ColField = value
                    Me.RaisePropertyChanged("Col")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustAssoc() As String
            Get
                Return Me.CustAssocField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustAssocField, value) <> true) Then
                    Me.CustAssocField = value
                    Me.RaisePropertyChanged("CustAssoc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsCallDetail() As Boolean
            Get
                Return Me.IsCallDetailField
            End Get
            Set
                If (Me.IsCallDetailField.Equals(value) <> true) Then
                    Me.IsCallDetailField = value
                    Me.RaisePropertyChanged("IsCallDetail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrgBranchList() As String
            Get
                Return Me.OrgBranchListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrgBranchListField, value) <> true) Then
                    Me.OrgBranchListField = value
                    Me.RaisePropertyChanged("OrgBranchList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrgFilterList() As String
            Get
                Return Me.OrgFilterListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrgFilterListField, value) <> true) Then
                    Me.OrgFilterListField = value
                    Me.RaisePropertyChanged("OrgFilterList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrgFilterType() As String
            Get
                Return Me.OrgFilterTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrgFilterTypeField, value) <> true) Then
                    Me.OrgFilterTypeField = value
                    Me.RaisePropertyChanged("OrgFilterType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrgType() As String
            Get
                Return Me.OrgTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrgTypeField, value) <> true) Then
                    Me.OrgTypeField = value
                    Me.RaisePropertyChanged("OrgType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Rows() As Integer()
            Get
                Return Me.RowsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RowsField, value) <> true) Then
                    Me.RowsField = value
                    Me.RaisePropertyChanged("Rows")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserId() As String
            Get
                Return Me.UserIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIdField, value) <> true) Then
                    Me.UserIdField = value
                    Me.RaisePropertyChanged("UserId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserPermission() As testDashUmm2Service.UserPermission
            Get
                Return Me.UserPermissionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserPermissionField, value) <> true) Then
                    Me.UserPermissionField = value
                    Me.RaisePropertyChanged("UserPermission")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VendorCode() As String
            Get
                Return Me.VendorCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VendorCodeField, value) <> true) Then
                    Me.VendorCodeField = value
                    Me.RaisePropertyChanged("VendorCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Col", [Namespace]:="http://schemas.datacontract.org/2004/07/WWTS.ServiceApp"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Col
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerCamparatorNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerCamparatorValueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubDivisionCamparatorNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubDivisionCamparatorValueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WorkOrderTypeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerCamparatorName() As String
            Get
                Return Me.CustomerCamparatorNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerCamparatorNameField, value) <> true) Then
                    Me.CustomerCamparatorNameField = value
                    Me.RaisePropertyChanged("CustomerCamparatorName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerCamparatorValue() As String
            Get
                Return Me.CustomerCamparatorValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerCamparatorValueField, value) <> true) Then
                    Me.CustomerCamparatorValueField = value
                    Me.RaisePropertyChanged("CustomerCamparatorValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubDivisionCamparatorName() As String
            Get
                Return Me.SubDivisionCamparatorNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubDivisionCamparatorNameField, value) <> true) Then
                    Me.SubDivisionCamparatorNameField = value
                    Me.RaisePropertyChanged("SubDivisionCamparatorName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubDivisionCamparatorValue() As String
            Get
                Return Me.SubDivisionCamparatorValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubDivisionCamparatorValueField, value) <> true) Then
                    Me.SubDivisionCamparatorValueField = value
                    Me.RaisePropertyChanged("SubDivisionCamparatorValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WorkOrderType() As String
            Get
                Return Me.WorkOrderTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WorkOrderTypeField, value) <> true) Then
                    Me.WorkOrderTypeField = value
                    Me.RaisePropertyChanged("WorkOrderType")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserPermission", [Namespace]:="http://schemas.datacontract.org/2004/07/WWTS.ServiceApp"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserPermission
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DashCustomerFilterOffField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DashVendorField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DashVendorFilterOffField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DashCustomerFilterOff() As Boolean
            Get
                Return Me.DashCustomerFilterOffField
            End Get
            Set
                If (Me.DashCustomerFilterOffField.Equals(value) <> true) Then
                    Me.DashCustomerFilterOffField = value
                    Me.RaisePropertyChanged("DashCustomerFilterOff")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DashVendor() As Boolean
            Get
                Return Me.DashVendorField
            End Get
            Set
                If (Me.DashVendorField.Equals(value) <> true) Then
                    Me.DashVendorField = value
                    Me.RaisePropertyChanged("DashVendor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DashVendorFilterOff() As Boolean
            Get
                Return Me.DashVendorFilterOffField
            End Get
            Set
                If (Me.DashVendorFilterOffField.Equals(value) <> true) Then
                    Me.DashVendorFilterOffField = value
                    Me.RaisePropertyChanged("DashVendorFilterOff")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FilterDetailData", [Namespace]:="http://schemas.datacontract.org/2004/07/WWTS.ServiceApp"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FilterDetailData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ColDatasField() As testDashUmm2Service.Col
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustAssocField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsCallDetailField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrgBranchListField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrgFilterListField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrgFilterTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrgTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RowsField() As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserPermissionField As testDashUmm2Service.UserPermission
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VendorCodeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ColDatas() As testDashUmm2Service.Col()
            Get
                Return Me.ColDatasField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ColDatasField, value) <> true) Then
                    Me.ColDatasField = value
                    Me.RaisePropertyChanged("ColDatas")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustAssoc() As String
            Get
                Return Me.CustAssocField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustAssocField, value) <> true) Then
                    Me.CustAssocField = value
                    Me.RaisePropertyChanged("CustAssoc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsCallDetail() As Boolean
            Get
                Return Me.IsCallDetailField
            End Get
            Set
                If (Me.IsCallDetailField.Equals(value) <> true) Then
                    Me.IsCallDetailField = value
                    Me.RaisePropertyChanged("IsCallDetail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrgBranchList() As String
            Get
                Return Me.OrgBranchListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrgBranchListField, value) <> true) Then
                    Me.OrgBranchListField = value
                    Me.RaisePropertyChanged("OrgBranchList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrgFilterList() As String
            Get
                Return Me.OrgFilterListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrgFilterListField, value) <> true) Then
                    Me.OrgFilterListField = value
                    Me.RaisePropertyChanged("OrgFilterList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrgFilterType() As String
            Get
                Return Me.OrgFilterTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrgFilterTypeField, value) <> true) Then
                    Me.OrgFilterTypeField = value
                    Me.RaisePropertyChanged("OrgFilterType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrgType() As String
            Get
                Return Me.OrgTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrgTypeField, value) <> true) Then
                    Me.OrgTypeField = value
                    Me.RaisePropertyChanged("OrgType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Rows() As Integer()
            Get
                Return Me.RowsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RowsField, value) <> true) Then
                    Me.RowsField = value
                    Me.RaisePropertyChanged("Rows")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserId() As String
            Get
                Return Me.UserIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIdField, value) <> true) Then
                    Me.UserIdField = value
                    Me.RaisePropertyChanged("UserId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserPermission() As testDashUmm2Service.UserPermission
            Get
                Return Me.UserPermissionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserPermissionField, value) <> true) Then
                    Me.UserPermissionField = value
                    Me.RaisePropertyChanged("UserPermission")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VendorCode() As String
            Get
                Return Me.VendorCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VendorCodeField, value) <> true) Then
                    Me.VendorCodeField = value
                    Me.RaisePropertyChanged("VendorCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="testDashUmm2Service.IDashSumm2Service")>  _
    Public Interface IDashSumm2Service
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDashSumm2Service/GetSummaryDataSample", ReplyAction:="http://tempuri.org/IDashSumm2Service/GetSummaryDataSampleResponse")>  _
        Function GetSummaryDataSample(ByVal filterData As testDashUmm2Service.FilterData) As WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDashSumm2Service/GetSummaryDataSample", ReplyAction:="http://tempuri.org/IDashSumm2Service/GetSummaryDataSampleResponse")>  _
        Function GetSummaryDataSampleAsync(ByVal filterData As testDashUmm2Service.FilterData) As System.Threading.Tasks.Task(Of WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDashSumm2Service/GetSummaryData", ReplyAction:="http://tempuri.org/IDashSumm2Service/GetSummaryDataResponse")>  _
        Function GetSummaryData(ByVal filterData As testDashUmm2Service.FilterData) As WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDashSumm2Service/GetSummaryData", ReplyAction:="http://tempuri.org/IDashSumm2Service/GetSummaryDataResponse")>  _
        Function GetSummaryDataAsync(ByVal filterData As testDashUmm2Service.FilterData) As System.Threading.Tasks.Task(Of WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDashSumm2Service/GetSummaryDetailData", ReplyAction:="http://tempuri.org/IDashSumm2Service/GetSummaryDetailDataResponse")>  _
        Function GetSummaryDetailData(ByVal filterData As testDashUmm2Service.FilterDetailData) As WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDashSumm2Service/GetSummaryDetailData", ReplyAction:="http://tempuri.org/IDashSumm2Service/GetSummaryDetailDataResponse")>  _
        Function GetSummaryDetailDataAsync(ByVal filterData As testDashUmm2Service.FilterDetailData) As System.Threading.Tasks.Task(Of WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IDashSumm2ServiceChannel
        Inherits testDashUmm2Service.IDashSumm2Service, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DashSumm2ServiceClient
        Inherits System.ServiceModel.ClientBase(Of testDashUmm2Service.IDashSumm2Service)
        Implements testDashUmm2Service.IDashSumm2Service
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetSummaryDataSample(ByVal filterData As testDashUmm2Service.FilterData) As WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData) Implements testDashUmm2Service.IDashSumm2Service.GetSummaryDataSample
            Return MyBase.Channel.GetSummaryDataSample(filterData)
        End Function
        
        Public Function GetSummaryDataSampleAsync(ByVal filterData As testDashUmm2Service.FilterData) As System.Threading.Tasks.Task(Of WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData)) Implements testDashUmm2Service.IDashSumm2Service.GetSummaryDataSampleAsync
            Return MyBase.Channel.GetSummaryDataSampleAsync(filterData)
        End Function
        
        Public Function GetSummaryData(ByVal filterData As testDashUmm2Service.FilterData) As WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData) Implements testDashUmm2Service.IDashSumm2Service.GetSummaryData
            Return MyBase.Channel.GetSummaryData(filterData)
        End Function
        
        Public Function GetSummaryDataAsync(ByVal filterData As testDashUmm2Service.FilterData) As System.Threading.Tasks.Task(Of WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData)) Implements testDashUmm2Service.IDashSumm2Service.GetSummaryDataAsync
            Return MyBase.Channel.GetSummaryDataAsync(filterData)
        End Function
        
        Public Function GetSummaryDetailData(ByVal filterData As testDashUmm2Service.FilterDetailData) As WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData) Implements testDashUmm2Service.IDashSumm2Service.GetSummaryDetailData
            Return MyBase.Channel.GetSummaryDetailData(filterData)
        End Function
        
        Public Function GetSummaryDetailDataAsync(ByVal filterData As testDashUmm2Service.FilterDetailData) As System.Threading.Tasks.Task(Of WWTS.Data.JsonResponse(Of WWTS.Data.Model.ColsData)) Implements testDashUmm2Service.IDashSumm2Service.GetSummaryDetailDataAsync
            Return MyBase.Channel.GetSummaryDetailDataAsync(filterData)
        End Function
    End Class
End Namespace
