'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [call]
    Public Property Dispatch_Number As String
    Public Property customer_number As String
    Public Property query_customer_number As String
    Public Property customer_name As String
    Public Property customer_address_1 As String
    Public Property customer_address_2 As String
    Public Property customer_address_3 As String
    Public Property customer_city As String
    Public Property customer_state As String
    Public Property customer_zip As String
    Public Property contact_name As String
    Public Property contact_phone As String
    Public Property employee_number As String
    Public Property employee_name As String
    Public Property call_type As String
    Public Property critical_verbage As String
    Public Property critical_code As String
    Public Property entitlement As String
    Public Property region_rdb As String
    Public Property district_rdb As String
    Public Property branch_rdb As String
    Public Property stop_code As String
    Public Property stop_code_indicator As String
    Public Property excuse_code As String
    Public Property wang_serial_number As String
    Public Property wang_model_number As String
    Public Property mfg_serial_number As String
    Public Property mfg_model_number As String
    Public Property system_number As String
    Public Property call_received_date As Nullable(Of Date)
    Public Property call_deferred_date As Nullable(Of Date)
    Public Property call_accepted_date As Nullable(Of Date)
    Public Property call_arrived_date As Nullable(Of Date)
    Public Property projected_arrival_date As Nullable(Of Date)
    Public Property call_dispatched_date As Nullable(Of Date)
    Public Property call_last_modified_date As Nullable(Of Date)
    Public Property call_status As String
    Public Property call_error_flag As String
    Public Property awp_code As String
    Public Property business_association_type As String
    Public Property oem_incident_number As String
    Public Property plan_code As String
    Public Property extended_coverage As String
    Public Property area_rdb As String
    Public Property SLA_Desc As Nullable(Of Byte)
    Public Property SLA_Color As Nullable(Of Byte)
    Public Property symptom_code As String
    Public Property Coverage_code As String
    Public Property datetimeloaded As Nullable(Of Date)
    Public Property timezone As Nullable(Of Decimal)
    Public Property actiongrp As String
    Public Property source As String
    Public Property vendor_callnbr As String
    Public Property stop_code_upd_dt As Nullable(Of Date)
    Public Property territory As String
    Public Property whse As String
    Public Property whsedist As Nullable(Of Integer)
    Public Property SRS_sched As String
    Public Property SKU As String
    Public Property install_qty As Nullable(Of Integer)
    Public Property sched_window_start_dt As Nullable(Of Date)
    Public Property sched_window_end_dt As Nullable(Of Date)
    Public Property cust_syscode As String
    Public Property customer_lat As Nullable(Of Decimal)
    Public Property customer_long As Nullable(Of Decimal)
    Public Property onsite_radius As Nullable(Of Integer)
    Public Property avg_repair_time As Nullable(Of Decimal)
    Public Property csr_cell_phone As String
    Public Property auto_onsite As String
    Public Property call_closed_date As Nullable(Of Date)
    Public Property last_call_Closed As String
    Public Property total_activities As Nullable(Of Integer)
    Public Property ready_date As Nullable(Of Date)
    Public Property cust_sub_div As String
    Public Property customer_country As String
    Public Property Purchase_Order As String
    Public Property customer_part_master As String
    Public Property cust_alt_ref As String
    Public Property required_skills As String
    Public Property initial_eta_dtm As Nullable(Of Date)
    Public Property contact_altphone As String
    Public Property altcontact_1stphone As String
    Public Property altcontact_2ndphone As String
    Public Property altcontact_name As String
    Public Property email_addr As String

End Class
