'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OpenWaybill
    Public Property rid As Integer
    Public Property OrderNum As String
    Public Property PartSeq As Integer
    Public Property ComDate As Nullable(Of Date)
    Public Property Region As String
    Public Property Area As String
    Public Property District As String
    Public Property Branch As String
    Public Property Territory As String
    Public Property EmployeeNo As String
    Public Property EmployeeName As String
    Public Property OEMIncNo As String
    Public Property CustCode As String
    Public Property CustName As String
    Public Property Subdivision As String
    Public Property PartRtnd As String
    Public Property PartRtndSN As String
    Public Property PartNo As String
    Public Property OrgQty As Nullable(Of Integer)
    Public Property UsedQty As Nullable(Of Integer)
    Public Property ReturnQty As Nullable(Of Integer)
    Public Property ActionCode As Nullable(Of Integer)
    Public Property NotReturnCode As String
    Public Property ReturnWayBill As String
    Public Property ReturnCarrier As String
    Public Property ReturnDate As Nullable(Of Date)
    Public Property RspCode As String
    Public Property UpdateFlag As String
    Public Property LastWebUpdate As Nullable(Of Date)
    Public Property CSRAsgnExcl As String
    Public Property ShowOnCSRPortal As String
    Public Property RtnWyblDispos As String
    Public Property DateTimeLoaded As Nullable(Of Date)
    Public Property Source As String
    Public Property CustPartRef As String

End Class
