'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class OneviewEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=OneviewEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property calls() As DbSet(Of [call])
    Public Overridable Property dtproperties() As DbSet(Of dtproperty)
    Public Overridable Property Logs() As DbSet(Of Log)
    Public Overridable Property OpenWaybills() As DbSet(Of OpenWaybill)
    Public Overridable Property ResponseCodes() As DbSet(Of ResponseCode)
    Public Overridable Property WyblDisposCodes() As DbSet(Of WyblDisposCode)
    Public Overridable Property tbl_csr_org() As DbSet(Of tbl_csr_org)

End Class
