'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WWTSService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/WWTS.ServiceApp"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseBase", [Namespace]:="http://schemas.datacontract.org/2004/07/WWTS.Data"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WWTSService.EmailLogDataResponse))>  _
    Partial Public Class ResponseBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsSuccessField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsSuccess() As Boolean
            Get
                Return Me.IsSuccessField
            End Get
            Set
                If (Me.IsSuccessField.Equals(value) <> true) Then
                    Me.IsSuccessField = value
                    Me.RaisePropertyChanged("IsSuccess")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EmailLogDataResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/WWTS.Data"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EmailLogDataResponse
        Inherits WWTSService.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultsField() As WWTSService.EmailLogData
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SingleResultField As WWTSService.EmailLogData
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalRecordCountField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Results() As WWTSService.EmailLogData()
            Get
                Return Me.ResultsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultsField, value) <> true) Then
                    Me.ResultsField = value
                    Me.RaisePropertyChanged("Results")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SingleResult() As WWTSService.EmailLogData
            Get
                Return Me.SingleResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SingleResultField, value) <> true) Then
                    Me.SingleResultField = value
                    Me.RaisePropertyChanged("SingleResult")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalRecordCount() As Integer
            Get
                Return Me.TotalRecordCountField
            End Get
            Set
                If (Me.TotalRecordCountField.Equals(value) <> true) Then
                    Me.TotalRecordCountField = value
                    Me.RaisePropertyChanged("TotalRecordCount")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EmailLogData", [Namespace]:="http://schemas.datacontract.org/2004/07/WWTS.Data.Model"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EmailLogData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BccEmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BccNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BodyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CcEmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CcNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CommentsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreatedDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailLogIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExpectedDeliveryDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FailedDeliveredAttemptesField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FromEmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FromNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsAttachmentField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsHtmlField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ModifiedDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PriorityField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RemarksField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubjectField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToEmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToNameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BccEmail() As String
            Get
                Return Me.BccEmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BccEmailField, value) <> true) Then
                    Me.BccEmailField = value
                    Me.RaisePropertyChanged("BccEmail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BccName() As String
            Get
                Return Me.BccNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BccNameField, value) <> true) Then
                    Me.BccNameField = value
                    Me.RaisePropertyChanged("BccName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Body() As String
            Get
                Return Me.BodyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BodyField, value) <> true) Then
                    Me.BodyField = value
                    Me.RaisePropertyChanged("Body")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CcEmail() As String
            Get
                Return Me.CcEmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CcEmailField, value) <> true) Then
                    Me.CcEmailField = value
                    Me.RaisePropertyChanged("CcEmail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CcName() As String
            Get
                Return Me.CcNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CcNameField, value) <> true) Then
                    Me.CcNameField = value
                    Me.RaisePropertyChanged("CcName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Comments() As String
            Get
                Return Me.CommentsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CommentsField, value) <> true) Then
                    Me.CommentsField = value
                    Me.RaisePropertyChanged("Comments")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreatedDate() As Date
            Get
                Return Me.CreatedDateField
            End Get
            Set
                If (Me.CreatedDateField.Equals(value) <> true) Then
                    Me.CreatedDateField = value
                    Me.RaisePropertyChanged("CreatedDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmailLogID() As Integer
            Get
                Return Me.EmailLogIDField
            End Get
            Set
                If (Me.EmailLogIDField.Equals(value) <> true) Then
                    Me.EmailLogIDField = value
                    Me.RaisePropertyChanged("EmailLogID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExpectedDeliveryDate() As System.Nullable(Of Date)
            Get
                Return Me.ExpectedDeliveryDateField
            End Get
            Set
                If (Me.ExpectedDeliveryDateField.Equals(value) <> true) Then
                    Me.ExpectedDeliveryDateField = value
                    Me.RaisePropertyChanged("ExpectedDeliveryDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FailedDeliveredAttemptes() As Integer
            Get
                Return Me.FailedDeliveredAttemptesField
            End Get
            Set
                If (Me.FailedDeliveredAttemptesField.Equals(value) <> true) Then
                    Me.FailedDeliveredAttemptesField = value
                    Me.RaisePropertyChanged("FailedDeliveredAttemptes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FromEmail() As String
            Get
                Return Me.FromEmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FromEmailField, value) <> true) Then
                    Me.FromEmailField = value
                    Me.RaisePropertyChanged("FromEmail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FromName() As String
            Get
                Return Me.FromNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FromNameField, value) <> true) Then
                    Me.FromNameField = value
                    Me.RaisePropertyChanged("FromName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsAttachment() As Boolean
            Get
                Return Me.IsAttachmentField
            End Get
            Set
                If (Me.IsAttachmentField.Equals(value) <> true) Then
                    Me.IsAttachmentField = value
                    Me.RaisePropertyChanged("IsAttachment")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsHtml() As Boolean
            Get
                Return Me.IsHtmlField
            End Get
            Set
                If (Me.IsHtmlField.Equals(value) <> true) Then
                    Me.IsHtmlField = value
                    Me.RaisePropertyChanged("IsHtml")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ModifiedDate() As System.Nullable(Of Date)
            Get
                Return Me.ModifiedDateField
            End Get
            Set
                If (Me.ModifiedDateField.Equals(value) <> true) Then
                    Me.ModifiedDateField = value
                    Me.RaisePropertyChanged("ModifiedDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Priority() As Integer
            Get
                Return Me.PriorityField
            End Get
            Set
                If (Me.PriorityField.Equals(value) <> true) Then
                    Me.PriorityField = value
                    Me.RaisePropertyChanged("Priority")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Remarks() As String
            Get
                Return Me.RemarksField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RemarksField, value) <> true) Then
                    Me.RemarksField = value
                    Me.RaisePropertyChanged("Remarks")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As Integer
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Subject() As String
            Get
                Return Me.SubjectField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubjectField, value) <> true) Then
                    Me.SubjectField = value
                    Me.RaisePropertyChanged("Subject")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ToEmail() As String
            Get
                Return Me.ToEmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToEmailField, value) <> true) Then
                    Me.ToEmailField = value
                    Me.RaisePropertyChanged("ToEmail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ToName() As String
            Get
                Return Me.ToNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToNameField, value) <> true) Then
                    Me.ToNameField = value
                    Me.RaisePropertyChanged("ToName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WWTSService.IWWTSService")>  _
    Public Interface IWWTSService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWWTSService/GetData", ReplyAction:="http://tempuri.org/IWWTSService/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWWTSService/GetData", ReplyAction:="http://tempuri.org/IWWTSService/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWWTSService/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IWWTSService/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As WWTSService.CompositeType) As WWTSService.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWWTSService/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IWWTSService/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As WWTSService.CompositeType) As System.Threading.Tasks.Task(Of WWTSService.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWWTSService/GetUserEmailLogs", ReplyAction:="http://tempuri.org/IWWTSService/GetUserEmailLogsResponse")>  _
        Function GetUserEmailLogs() As WWTSService.EmailLogDataResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWWTSService/GetUserEmailLogs", ReplyAction:="http://tempuri.org/IWWTSService/GetUserEmailLogsResponse")>  _
        Function GetUserEmailLogsAsync() As System.Threading.Tasks.Task(Of WWTSService.EmailLogDataResponse)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWWTSServiceChannel
        Inherits WWTSService.IWWTSService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WWTSServiceClient
        Inherits System.ServiceModel.ClientBase(Of WWTSService.IWWTSService)
        Implements WWTSService.IWWTSService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements WWTSService.IWWTSService.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements WWTSService.IWWTSService.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As WWTSService.CompositeType) As WWTSService.CompositeType Implements WWTSService.IWWTSService.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As WWTSService.CompositeType) As System.Threading.Tasks.Task(Of WWTSService.CompositeType) Implements WWTSService.IWWTSService.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
        
        Public Function GetUserEmailLogs() As WWTSService.EmailLogDataResponse Implements WWTSService.IWWTSService.GetUserEmailLogs
            Return MyBase.Channel.GetUserEmailLogs
        End Function
        
        Public Function GetUserEmailLogsAsync() As System.Threading.Tasks.Task(Of WWTSService.EmailLogDataResponse) Implements WWTSService.IWWTSService.GetUserEmailLogsAsync
            Return MyBase.Channel.GetUserEmailLogsAsync
        End Function
    End Class
End Namespace
